services:
  - type: web
    name: your-app-name
    env: docker
    plan: free

    buildCommand: |
      docker build \
        --build-arg VITE_BASE_URL=$VITE_BASE_URL \
        -t your-app .

    startCommand: npm run start

    envVars:
      - key: VITE_BASE_URL
        value: https://fullstack-ia7o.onrender.com
